Update reference.documentize.com-metadata.yml

diff --git a/.github/workflows/reference.documentize.com-metadata.yml b/.github/workflows/reference.documentize.com-metadata.yml
--- a/.github/workflows/reference.documentize.com-metadata.yml
+++ b/.github/workflows/reference.documentize.com-metadata.yml
@@ -94,21 +94,18 @@ jobs:
       run: |
         echo "Running DocFX metadata command"
         .\docfx metadata --logLevel Warning || echo "DocFX failed with exit code %ERRORLEVEL%"
-        echo "Listing contents of docfx_input directory after running DocFX"
+        echo "Listing docfx_input directory:"
         dir temp_folder\docfx_input
-
-    - name: Verify API folder
-      run: |
-        echo "Verifying existence of 'api' or 'API' folder in docfx_input"
+        echo "Checking for api or API folder"
         if (Test-Path -Path temp_folder\docfx_input\api) {
-          echo "'api' folder found in expected location"
-          dir temp_folder\docfx_input\api
+            echo "Found api folder"
+            dir temp_folder\docfx_input\api
         } elseif (Test-Path -Path temp_folder\docfx_input\API) {
-          echo "'API' folder found in expected location"
-          dir temp_folder\docfx_input\API
+            echo "Found API folder"
+            dir temp_folder\docfx_input\API
         } else {
-          echo "Error: No 'api' or 'API' folder found after running DocFX"
-          exit 1
+            echo "Error: No API output directory found"
+            exit 1
         }
 
     - name: Run Python script
